// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoqYlKp6JWdhlkLinLU8X8TEbiiFmo_Fo',
    appId: '1:734490706940:web:4815044dcd869e6d9b6879',
    messagingSenderId: '734490706940',
    projectId: 'food-quest-ec947',
    authDomain: 'food-quest-ec947.firebaseapp.com',
    storageBucket: 'food-quest-ec947.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApBokvXhsrVfCwXch056qCeTHJ8acdFXo',
    appId: '1:734490706940:android:4bda2bf19176ebd39b6879',
    messagingSenderId: '734490706940',
    projectId: 'food-quest-ec947',
    storageBucket: 'food-quest-ec947.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABI7cp8zsULkT6hgmb6AkxA29z5cNm-bs',
    appId: '1:734490706940:ios:da0bb2576b8c700f9b6879',
    messagingSenderId: '734490706940',
    projectId: 'food-quest-ec947',
    storageBucket: 'food-quest-ec947.appspot.com',
    iosBundleId: 'com.example.foodQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABI7cp8zsULkT6hgmb6AkxA29z5cNm-bs',
    appId: '1:734490706940:ios:da0bb2576b8c700f9b6879',
    messagingSenderId: '734490706940',
    projectId: 'food-quest-ec947',
    storageBucket: 'food-quest-ec947.appspot.com',
    iosBundleId: 'com.example.foodQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoqYlKp6JWdhlkLinLU8X8TEbiiFmo_Fo',
    appId: '1:734490706940:web:c0e25a10edb276d99b6879',
    messagingSenderId: '734490706940',
    projectId: 'food-quest-ec947',
    authDomain: 'food-quest-ec947.firebaseapp.com',
    storageBucket: 'food-quest-ec947.appspot.com',
  );
}
